language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm i npm@latest -g
  - npm install

script:
  - ng build --prod
