language: node_js
node_js:
- '8'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  ssh_known_hosts: back1.igotta.beer
install:
- npm i npm@latest -g
- npm install
script:
- ng build --prod
before_deploy:
- cd deploy
- openssl aes-256-cbc -K $encrypted_1154f5ca60b7_key -iv $encrypted_1154f5ca60b7_iv -in deploy_rsa.enc -out deploy_rsa -d
- cd ..
- eval "$(ssh-agent -s)"
- chmod 600 deploy/deploy_rsa
- ssh-add deploy/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash deploy/travis_deploy.sh $TRAVIS_BUILD_DIR
  on:
branch: master
