language: node_js
node_js:
- '8'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  ssh_known_hosts: front1.igotta.beer
install:
- npm i npm@latest -g
- npm install
script:
- ng build --prod
before_deploy:
- openssl aes-256-cbc -K $encrypted_c655a7037c79_key -iv $encrypted_c655a7037c79_iv  -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash deploy/travis_deploy.sh $TRAVIS_BUILD_DIR
  on:
branch: master
